version: "3.7"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: myonara/webmud3:seifenblase
    environment: 
      NODE_ENV: 'production'
      SECRET_CONFIG: '/run/webmud3sb.json'
    volumes:
      - "/UNItopia/ftpwww/webmud3/run:/run"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: seife.mud.de
        com.docker.lb.network: webnetsb
        com.docker.lb.port: 2020
      restart_policy:
        condition: on-failure
    ports:
      - "2020:5000"
    networks:
      - webnetsb
networks:
  webnetsb:
    driver: overlay
    attachable: true
