version: "3.7"
services:
  web:
    image: myonara/webmud3:unitopiatest
    environment: 
      NODE_ENV: 'production'
      SECRET_CONFIG: '/run/webmud3test.json'
      MUD_CONFIG: '/run/mud_config_unitopia_test.json'
      WEBMUD3_DISTRIBUTION_TYPE: 'unitopia-test'
    volumes:
      - "/UNItopia/ftpwww/webmud3/run:/run"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      labels:
        com.docker.lb.hosts: www.unitopia.de
        com.docker.lb.network: webnet
        com.docker.lb.port: 2019
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 2 
        window: 3600s
    ports:
      - "2019:5000"
    networks:
      - webnet
networks:
  webnet:
    attachable: true
